version: 0.2

env:
  variables:
    TERRAFORM_CODE_SRC_DIR: terraform_code/EcsCluster
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/${TERRAFORM_CODE_SRC_DIR}
      - echo "## TERRAFORM APPLY = Starting with the Terraform Apply"
      - terraform init
      - terraform apply --auto-approve -input=false tfapply

artifacts:
  files:
    - '**/*'