version: 0.2

env:
  variables:
    TERRAFORM_CODE_SRC_DIR: terraform_code/EcsCluster
    API_CODE_SRC_DIR: api
    AWS_DEFAULT_REGION: "us-east-1"
    REPOSITORYNAME: "name"
    CLUSTERNAME: "pt1"
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install poetry
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/${API_CODE_SRC_DIR}
      - tagname=$(poetry version -s)
      - cd ${CODEBUILD_SRC_DIR}/${TERRAFORM_CODE_SRC_DIR}
      - terraform init
      - echo "## TERRAFORM PLAN = Generate the Terraform Plan"
      - terraform plan -var "clusterName=${CLUSTERNAME}" -var "repositoryVersion=${tagname}" -var "region=${AWS_DEFAULT_REGION}" -out tfapply
artifacts:
  files:
    - '**/*'